# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ------------------------------------------
# Kubernetes
# ------------------------------------------

alias k='kubectl'
alias ka='kubectl apply --recursive -f'
alias kak='kubectl apply -k'
alias kd='kubectl describe'
alias kdall='kubectl describe --all-namespaces'
alias kdcm='kubectl describe configmap'
alias kdcmall='kubectl describe configmap --all-namespaces'
alias kdcml='kubectl describe configmap -l'
alias kdcmn='kubectl describe configmap --namespace'
alias kddep='kubectl describe deployment'
alias kddepall='kubectl describe deployment --all-namespaces'
alias kddepl='kubectl describe deployment -l'
alias kddepn='kubectl describe deployment --namespace'
alias kdf='kubectl describe --recursive -f'
alias kding='kubectl describe ingress'
alias kdingall='kubectl describe ingress --all-namespaces'
alias kdingl='kubectl describe ingress -l'
alias kdingn='kubectl describe ingress --namespace'
alias kdl='kubectl describe -l'
alias kdn='kubectl describe --namespace'
alias kdno='kubectl describe nodes'
alias kdnol='kubectl describe nodes -l'
alias kdns='kubectl describe namespaces'
alias kdnsl='kubectl describe namespaces -l'
alias kdpo='kubectl describe pods'
alias kdpoall='kubectl describe pods --all-namespaces'
alias kdpol='kubectl describe pods -l'
alias kdpon='kubectl describe pods --namespace'
alias kdsec='kubectl describe secret'
alias kdsecall='kubectl describe secret --all-namespaces'
alias kdsecl='kubectl describe secret -l'
alias kdsecn='kubectl describe secret --namespace'
alias kdsts='kubectl describe statefulset'
alias kdstsall='kubectl describe statefulset --all-namespaces'
alias kdstsl='kubectl describe statefulset -l'
alias kdstsn='kubectl describe statefulset --namespace'
alias kdsvc='kubectl describe service'
alias kdsvcall='kubectl describe service --all-namespaces'
alias kdsvcl='kubectl describe service -l'
alias kdsvcn='kubectl describe service --namespace'
alias kex='kubectl exec -i -t'
alias kexn='kubectl exec -i -t --namespace'
alias kg='kubectl get'
alias kgall='kubectl get --all-namespaces'
alias kgallojson='kubectl get --all-namespaces -o=json'
alias kgallowide='kubectl get --all-namespaces -o=wide'
alias kgallowidesl='kubectl get --all-namespaces -o=wide --show-labels'
alias kgalloyaml='kubectl get --all-namespaces -o=yaml'
alias kgallsl='kubectl get --all-namespaces --show-labels'
alias kgallslowide='kubectl get --all-namespaces --show-labels -o=wide'
alias kgallslw='kubectl get --all-namespaces --show-labels --watch'
alias kgallw='kubectl get --all-namespaces --watch'
alias kgallwsl='kubectl get --all-namespaces --watch --show-labels'
alias kgcm='kubectl get configmap'
alias kgcmall='kubectl get configmap --all-namespaces'
alias kgcmallojson='kubectl get configmap --all-namespaces -o=json'
alias kgcmallowide='kubectl get configmap --all-namespaces -o=wide'
alias kgcmallowidesl='kubectl get configmap --all-namespaces -o=wide --show-labels'
alias kgcmalloyaml='kubectl get configmap --all-namespaces -o=yaml'
alias kgcmallsl='kubectl get configmap --all-namespaces --show-labels'
alias kgcmallslowide='kubectl get configmap --all-namespaces --show-labels -o=wide'
alias kgcmallslw='kubectl get configmap --all-namespaces --show-labels --watch'
alias kgcmallw='kubectl get configmap --all-namespaces --watch'
alias kgcmallwsl='kubectl get configmap --all-namespaces --watch --show-labels'
alias kgcml='kubectl get configmap -l'
alias kgcmn='kubectl get configmap --namespace'
alias kgcmojson='kubectl get configmap -o=json'
alias kgcmojsonall='kubectl get configmap -o=json --all-namespaces'
alias kgcmojsonl='kubectl get configmap -o=json -l'
alias kgcmojsonn='kubectl get configmap -o=json --namespace'
alias kgcmowide='kubectl get configmap -o=wide'
alias kgcmowideall='kubectl get configmap -o=wide --all-namespaces'
alias kgcmowideallsl='kubectl get configmap -o=wide --all-namespaces --show-labels'
alias kgcmowidel='kubectl get configmap -o=wide -l'
alias kgcmowiden='kubectl get configmap -o=wide --namespace'
alias kgcmowidesl='kubectl get configmap -o=wide --show-labels'
alias kgcmowideslall='kubectl get configmap -o=wide --show-labels --all-namespaces'
alias kgcmowidesll='kubectl get configmap -o=wide --show-labels -l'
alias kgcmowidesln='kubectl get configmap -o=wide --show-labels --namespace'
alias kgcmoyaml='kubectl get configmap -o=yaml'
alias kgcmoyamlall='kubectl get configmap -o=yaml --all-namespaces'
alias kgcmoyamll='kubectl get configmap -o=yaml -l'
alias kgcmoyamln='kubectl get configmap -o=yaml --namespace'
alias kgcmsl='kubectl get configmap --show-labels'
alias kgcmslall='kubectl get configmap --show-labels --all-namespaces'
alias kgcmslallowide='kubectl get configmap --show-labels --all-namespaces -o=wide'
alias kgcmslallw='kubectl get configmap --show-labels --all-namespaces --watch'
alias kgcmsll='kubectl get configmap --show-labels -l'
alias kgcmsln='kubectl get configmap --show-labels --namespace'
alias kgcmslowide='kubectl get configmap --show-labels -o=wide'
alias kgcmslowideall='kubectl get configmap --show-labels -o=wide --all-namespaces'
alias kgcmslowidel='kubectl get configmap --show-labels -o=wide -l'
alias kgcmslowiden='kubectl get configmap --show-labels -o=wide --namespace'
alias kgcmslw='kubectl get configmap --show-labels --watch'
alias kgcmslwall='kubectl get configmap --show-labels --watch --all-namespaces'
alias kgcmslwl='kubectl get configmap --show-labels --watch -l'
alias kgcmslwn='kubectl get configmap --show-labels --watch --namespace'
alias kgcmw='kubectl get configmap --watch'
alias kgcmwall='kubectl get configmap --watch --all-namespaces'
alias kgcmwallsl='kubectl get configmap --watch --all-namespaces --show-labels'
alias kgcmwl='kubectl get configmap --watch -l'
alias kgcmwn='kubectl get configmap --watch --namespace'
alias kgcmwsl='kubectl get configmap --watch --show-labels'
alias kgcmwslall='kubectl get configmap --watch --show-labels --all-namespaces'
alias kgcmwsll='kubectl get configmap --watch --show-labels -l'
alias kgcmwsln='kubectl get configmap --watch --show-labels --namespace'
alias kgdep='kubectl get deployment'
alias kgdepall='kubectl get deployment --all-namespaces'
alias kgdepallojson='kubectl get deployment --all-namespaces -o=json'
alias kgdepallowide='kubectl get deployment --all-namespaces -o=wide'
alias kgdepallowidesl='kubectl get deployment --all-namespaces -o=wide --show-labels'
alias kgdepalloyaml='kubectl get deployment --all-namespaces -o=yaml'
alias kgdepallsl='kubectl get deployment --all-namespaces --show-labels'
alias kgdepallslowide='kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgdepallslw='kubectl get deployment --all-namespaces --show-labels --watch'
alias kgdepallw='kubectl get deployment --all-namespaces --watch'
alias kgdepallwsl='kubectl get deployment --all-namespaces --watch --show-labels'
alias kgdepl='kubectl get deployment -l'
alias kgdepn='kubectl get deployment --namespace'
alias kgdepojson='kubectl get deployment -o=json'
alias kgdepojsonall='kubectl get deployment -o=json --all-namespaces'
alias kgdepojsonl='kubectl get deployment -o=json -l'
alias kgdepojsonn='kubectl get deployment -o=json --namespace'
alias kgdepowide='kubectl get deployment -o=wide'
alias kgdepowideall='kubectl get deployment -o=wide --all-namespaces'
alias kgdepowideallsl='kubectl get deployment -o=wide --all-namespaces --show-labels'
alias kgdepowidel='kubectl get deployment -o=wide -l'
alias kgdepowiden='kubectl get deployment -o=wide --namespace'
alias kgdepowidesl='kubectl get deployment -o=wide --show-labels'
alias kgdepowideslall='kubectl get deployment -o=wide --show-labels --all-namespaces'
alias kgdepowidesll='kubectl get deployment -o=wide --show-labels -l'
alias kgdepowidesln='kubectl get deployment -o=wide --show-labels --namespace'
alias kgdepoyaml='kubectl get deployment -o=yaml'
alias kgdepoyamlall='kubectl get deployment -o=yaml --all-namespaces'
alias kgdepoyamll='kubectl get deployment -o=yaml -l'
alias kgdepoyamln='kubectl get deployment -o=yaml --namespace'
alias kgdepsl='kubectl get deployment --show-labels'
alias kgdepslall='kubectl get deployment --show-labels --all-namespaces'
alias kgdepslallowide='kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgdepslallw='kubectl get deployment --show-labels --all-namespaces --watch'
alias kgdepsll='kubectl get deployment --show-labels -l'
alias kgdepsln='kubectl get deployment --show-labels --namespace'
alias kgdepslowide='kubectl get deployment --show-labels -o=wide'
alias kgdepslowideall='kubectl get deployment --show-labels -o=wide --all-namespaces'
alias kgdepslowidel='kubectl get deployment --show-labels -o=wide -l'
alias kgdepslowiden='kubectl get deployment --show-labels -o=wide --namespace'
alias kgdepslw='kubectl get deployment --show-labels --watch'
alias kgdepslwall='kubectl get deployment --show-labels --watch --all-namespaces'
alias kgdepslwl='kubectl get deployment --show-labels --watch -l'
alias kgdepslwn='kubectl get deployment --show-labels --watch --namespace'
alias kgdepw='kubectl get deployment --watch'
alias kgdepwall='kubectl get deployment --watch --all-namespaces'
alias kgdepwallsl='kubectl get deployment --watch --all-namespaces --show-labels'
alias kgdepwl='kubectl get deployment --watch -l'
alias kgdepwn='kubectl get deployment --watch --namespace'
alias kgdepwsl='kubectl get deployment --watch --show-labels'
alias kgdepwslall='kubectl get deployment --watch --show-labels --all-namespaces'
alias kgdepwsll='kubectl get deployment --watch --show-labels -l'
alias kgdepwsln='kubectl get deployment --watch --show-labels --namespace'
alias kgf='kubectl get --recursive -f'
alias kging='kubectl get ingress'
alias kgingall='kubectl get ingress --all-namespaces'
alias kgingallojson='kubectl get ingress --all-namespaces -o=json'
alias kgingallowide='kubectl get ingress --all-namespaces -o=wide'
alias kgingallowidesl='kubectl get ingress --all-namespaces -o=wide --show-labels'
alias kgingalloyaml='kubectl get ingress --all-namespaces -o=yaml'
alias kgingallsl='kubectl get ingress --all-namespaces --show-labels'
alias kgingallslowide='kubectl get ingress --all-namespaces --show-labels -o=wide'
alias kgingallslw='kubectl get ingress --all-namespaces --show-labels --watch'
alias kgingallw='kubectl get ingress --all-namespaces --watch'
alias kgingallwsl='kubectl get ingress --all-namespaces --watch --show-labels'
alias kgingl='kubectl get ingress -l'
alias kgingn='kubectl get ingress --namespace'
alias kgingojson='kubectl get ingress -o=json'
alias kgingojsonall='kubectl get ingress -o=json --all-namespaces'
alias kgingojsonl='kubectl get ingress -o=json -l'
alias kgingojsonn='kubectl get ingress -o=json --namespace'
alias kgingowide='kubectl get ingress -o=wide'
alias kgingowideall='kubectl get ingress -o=wide --all-namespaces'
alias kgingowideallsl='kubectl get ingress -o=wide --all-namespaces --show-labels'
alias kgingowidel='kubectl get ingress -o=wide -l'
alias kgingowiden='kubectl get ingress -o=wide --namespace'
alias kgingowidesl='kubectl get ingress -o=wide --show-labels'
alias kgingowideslall='kubectl get ingress -o=wide --show-labels --all-namespaces'
alias kgingowidesll='kubectl get ingress -o=wide --show-labels -l'
alias kgingowidesln='kubectl get ingress -o=wide --show-labels --namespace'
alias kgingoyaml='kubectl get ingress -o=yaml'
alias kgingoyamlall='kubectl get ingress -o=yaml --all-namespaces'
alias kgingoyamll='kubectl get ingress -o=yaml -l'
alias kgingoyamln='kubectl get ingress -o=yaml --namespace'
alias kgingsl='kubectl get ingress --show-labels'
alias kgingslall='kubectl get ingress --show-labels --all-namespaces'
alias kgingslallowide='kubectl get ingress --show-labels --all-namespaces -o=wide'
alias kgingslallw='kubectl get ingress --show-labels --all-namespaces --watch'
alias kgingsll='kubectl get ingress --show-labels -l'
alias kgingsln='kubectl get ingress --show-labels --namespace'
alias kgingslowide='kubectl get ingress --show-labels -o=wide'
alias kgingslowideall='kubectl get ingress --show-labels -o=wide --all-namespaces'
alias kgingslowidel='kubectl get ingress --show-labels -o=wide -l'
alias kgingslowiden='kubectl get ingress --show-labels -o=wide --namespace'
alias kgingslw='kubectl get ingress --show-labels --watch'
alias kgingslwall='kubectl get ingress --show-labels --watch --all-namespaces'
alias kgingslwl='kubectl get ingress --show-labels --watch -l'
alias kgingslwn='kubectl get ingress --show-labels --watch --namespace'
alias kgingw='kubectl get ingress --watch'
alias kgingwall='kubectl get ingress --watch --all-namespaces'
alias kgingwallsl='kubectl get ingress --watch --all-namespaces --show-labels'
alias kgingwl='kubectl get ingress --watch -l'
alias kgingwn='kubectl get ingress --watch --namespace'
alias kgingwsl='kubectl get ingress --watch --show-labels'
alias kgingwslall='kubectl get ingress --watch --show-labels --all-namespaces'
alias kgingwsll='kubectl get ingress --watch --show-labels -l'
alias kgingwsln='kubectl get ingress --watch --show-labels --namespace'
alias kgl='kubectl get -l'
alias kgn='kubectl get --namespace'
alias kgno='kubectl get nodes'
alias kgnol='kubectl get nodes -l'
alias kgnoojson='kubectl get nodes -o=json'
alias kgnoojsonl='kubectl get nodes -o=json -l'
alias kgnoowide='kubectl get nodes -o=wide'
alias kgnoowidel='kubectl get nodes -o=wide -l'
alias kgnoowidesl='kubectl get nodes -o=wide --show-labels'
alias kgnoowidesll='kubectl get nodes -o=wide --show-labels -l'
alias kgnooyaml='kubectl get nodes -o=yaml'
alias kgnooyamll='kubectl get nodes -o=yaml -l'
alias kgnosl='kubectl get nodes --show-labels'
alias kgnosll='kubectl get nodes --show-labels -l'
alias kgnoslowide='kubectl get nodes --show-labels -o=wide'
alias kgnoslowidel='kubectl get nodes --show-labels -o=wide -l'
alias kgnoslw='kubectl get nodes --show-labels --watch'
alias kgnoslwl='kubectl get nodes --show-labels --watch -l'
alias kgnow='kubectl get nodes --watch'
alias kgnowl='kubectl get nodes --watch -l'
alias kgnowsl='kubectl get nodes --watch --show-labels'
alias kgnowsll='kubectl get nodes --watch --show-labels -l'
alias kgns='kubectl get namespaces'
alias kgnsl='kubectl get namespaces -l'
alias kgnsojson='kubectl get namespaces -o=json'
alias kgnsojsonl='kubectl get namespaces -o=json -l'
alias kgnsowide='kubectl get namespaces -o=wide'
alias kgnsowidel='kubectl get namespaces -o=wide -l'
alias kgnsowidesl='kubectl get namespaces -o=wide --show-labels'
alias kgnsowidesll='kubectl get namespaces -o=wide --show-labels -l'
alias kgnsoyaml='kubectl get namespaces -o=yaml'
alias kgnsoyamll='kubectl get namespaces -o=yaml -l'
alias kgnssl='kubectl get namespaces --show-labels'
alias kgnssll='kubectl get namespaces --show-labels -l'
alias kgnsslowide='kubectl get namespaces --show-labels -o=wide'
alias kgnsslowidel='kubectl get namespaces --show-labels -o=wide -l'
alias kgnsslw='kubectl get namespaces --show-labels --watch'
alias kgnsslwl='kubectl get namespaces --show-labels --watch -l'
alias kgnsw='kubectl get namespaces --watch'
alias kgnswl='kubectl get namespaces --watch -l'
alias kgnswsl='kubectl get namespaces --watch --show-labels'
alias kgnswsll='kubectl get namespaces --watch --show-labels -l'
alias kgojson='kubectl get -o=json'
alias kgojsonall='kubectl get -o=json --all-namespaces'
alias kgojsonf='kubectl get -o=json --recursive -f'
alias kgojsonl='kubectl get -o=json -l'
alias kgojsonn='kubectl get -o=json --namespace'
alias kgowide='kubectl get -o=wide'
alias kgowideall='kubectl get -o=wide --all-namespaces'
alias kgowideallsl='kubectl get -o=wide --all-namespaces --show-labels'
alias kgowidef='kubectl get -o=wide --recursive -f'
alias kgowidel='kubectl get -o=wide -l'
alias kgowiden='kubectl get -o=wide --namespace'
alias kgowidesl='kubectl get -o=wide --show-labels'
alias kgowideslall='kubectl get -o=wide --show-labels --all-namespaces'
alias kgowideslf='kubectl get -o=wide --show-labels --recursive -f'
alias kgowidesll='kubectl get -o=wide --show-labels -l'
alias kgowidesln='kubectl get -o=wide --show-labels --namespace'
alias kgoyaml='kubectl get -o=yaml'
alias kgoyamlall='kubectl get -o=yaml --all-namespaces'
alias kgoyamlf='kubectl get -o=yaml --recursive -f'
alias kgoyamll='kubectl get -o=yaml -l'
alias kgoyamln='kubectl get -o=yaml --namespace'
alias kgpo='kubectl get pods'
alias kgpoall='kubectl get pods --all-namespaces'
alias kgpoallojson='kubectl get pods --all-namespaces -o=json'
alias kgpoallowide='kubectl get pods --all-namespaces -o=wide'
alias kgpoallowidesl='kubectl get pods --all-namespaces -o=wide --show-labels'
alias kgpoalloyaml='kubectl get pods --all-namespaces -o=yaml'
alias kgpoallsl='kubectl get pods --all-namespaces --show-labels'
alias kgpoallslowide='kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgpoallslw='kubectl get pods --all-namespaces --show-labels --watch'
alias kgpoallw='kubectl get pods --all-namespaces --watch'
alias kgpoallwsl='kubectl get pods --all-namespaces --watch --show-labels'
alias kgpol='kubectl get pods -l'
alias kgpon='kubectl get pods --namespace'
alias kgpoojson='kubectl get pods -o=json'
alias kgpoojsonall='kubectl get pods -o=json --all-namespaces'
alias kgpoojsonl='kubectl get pods -o=json -l'
alias kgpoojsonn='kubectl get pods -o=json --namespace'
alias kgpoowide='kubectl get pods -o=wide'
alias kgpoowideall='kubectl get pods -o=wide --all-namespaces'
alias kgpoowideallsl='kubectl get pods -o=wide --all-namespaces --show-labels'
alias kgpoowidel='kubectl get pods -o=wide -l'
alias kgpoowiden='kubectl get pods -o=wide --namespace'
alias kgpoowidesl='kubectl get pods -o=wide --show-labels'
alias kgpoowideslall='kubectl get pods -o=wide --show-labels --all-namespaces'
alias kgpoowidesll='kubectl get pods -o=wide --show-labels -l'
alias kgpoowidesln='kubectl get pods -o=wide --show-labels --namespace'
alias kgpooyaml='kubectl get pods -o=yaml'
alias kgpooyamlall='kubectl get pods -o=yaml --all-namespaces'
alias kgpooyamll='kubectl get pods -o=yaml -l'
alias kgpooyamln='kubectl get pods -o=yaml --namespace'
alias kgposl='kubectl get pods --show-labels'
alias kgposlall='kubectl get pods --show-labels --all-namespaces'
alias kgposlallowide='kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgposlallw='kubectl get pods --show-labels --all-namespaces --watch'
alias kgposll='kubectl get pods --show-labels -l'
alias kgposln='kubectl get pods --show-labels --namespace'
alias kgposlowide='kubectl get pods --show-labels -o=wide'
alias kgposlowideall='kubectl get pods --show-labels -o=wide --all-namespaces'
alias kgposlowidel='kubectl get pods --show-labels -o=wide -l'
alias kgposlowiden='kubectl get pods --show-labels -o=wide --namespace'
alias kgposlw='kubectl get pods --show-labels --watch'
alias kgposlwall='kubectl get pods --show-labels --watch --all-namespaces'
alias kgposlwl='kubectl get pods --show-labels --watch -l'
alias kgposlwn='kubectl get pods --show-labels --watch --namespace'
alias kgpow='kubectl get pods --watch'
alias kgpowall='kubectl get pods --watch --all-namespaces'
alias kgpowallsl='kubectl get pods --watch --all-namespaces --show-labels'
alias kgpowl='kubectl get pods --watch -l'
alias kgpown='kubectl get pods --watch --namespace'
alias kgpowsl='kubectl get pods --watch --show-labels'
alias kgpowslall='kubectl get pods --watch --show-labels --all-namespaces'
alias kgpowsll='kubectl get pods --watch --show-labels -l'
alias kgpowsln='kubectl get pods --watch --show-labels --namespace'
alias kgsec='kubectl get secret'
alias kgsecall='kubectl get secret --all-namespaces'
alias kgsecallojson='kubectl get secret --all-namespaces -o=json'
alias kgsecallowide='kubectl get secret --all-namespaces -o=wide'
alias kgsecallowidesl='kubectl get secret --all-namespaces -o=wide --show-labels'
alias kgsecalloyaml='kubectl get secret --all-namespaces -o=yaml'
alias kgsecallsl='kubectl get secret --all-namespaces --show-labels'
alias kgsecallslowide='kubectl get secret --all-namespaces --show-labels -o=wide'
alias kgsecallslw='kubectl get secret --all-namespaces --show-labels --watch'
alias kgsecallw='kubectl get secret --all-namespaces --watch'
alias kgsecallwsl='kubectl get secret --all-namespaces --watch --show-labels'
alias kgsecl='kubectl get secret -l'
alias kgsecn='kubectl get secret --namespace'
alias kgsecojson='kubectl get secret -o=json'
alias kgsecojsonall='kubectl get secret -o=json --all-namespaces'
alias kgsecojsonl='kubectl get secret -o=json -l'
alias kgsecojsonn='kubectl get secret -o=json --namespace'
alias kgsecowide='kubectl get secret -o=wide'
alias kgsecowideall='kubectl get secret -o=wide --all-namespaces'
alias kgsecowideallsl='kubectl get secret -o=wide --all-namespaces --show-labels'
alias kgsecowidel='kubectl get secret -o=wide -l'
alias kgsecowiden='kubectl get secret -o=wide --namespace'
alias kgsecowidesl='kubectl get secret -o=wide --show-labels'
alias kgsecowideslall='kubectl get secret -o=wide --show-labels --all-namespaces'
alias kgsecowidesll='kubectl get secret -o=wide --show-labels -l'
alias kgsecowidesln='kubectl get secret -o=wide --show-labels --namespace'
alias kgsecoyaml='kubectl get secret -o=yaml'
alias kgsecoyamlall='kubectl get secret -o=yaml --all-namespaces'
alias kgsecoyamll='kubectl get secret -o=yaml -l'
alias kgsecoyamln='kubectl get secret -o=yaml --namespace'
alias kgsecsl='kubectl get secret --show-labels'
alias kgsecslall='kubectl get secret --show-labels --all-namespaces'
alias kgsecslallowide='kubectl get secret --show-labels --all-namespaces -o=wide'
alias kgsecslallw='kubectl get secret --show-labels --all-namespaces --watch'
alias kgsecsll='kubectl get secret --show-labels -l'
alias kgsecsln='kubectl get secret --show-labels --namespace'
alias kgsecslowide='kubectl get secret --show-labels -o=wide'
alias kgsecslowideall='kubectl get secret --show-labels -o=wide --all-namespaces'
alias kgsecslowidel='kubectl get secret --show-labels -o=wide -l'
alias kgsecslowiden='kubectl get secret --show-labels -o=wide --namespace'
alias kgsecslw='kubectl get secret --show-labels --watch'
alias kgsecslwall='kubectl get secret --show-labels --watch --all-namespaces'
alias kgsecslwl='kubectl get secret --show-labels --watch -l'
alias kgsecslwn='kubectl get secret --show-labels --watch --namespace'
alias kgsecw='kubectl get secret --watch'
alias kgsecwall='kubectl get secret --watch --all-namespaces'
alias kgsecwallsl='kubectl get secret --watch --all-namespaces --show-labels'
alias kgsecwl='kubectl get secret --watch -l'
alias kgsecwn='kubectl get secret --watch --namespace'
alias kgsecwsl='kubectl get secret --watch --show-labels'
alias kgsecwslall='kubectl get secret --watch --show-labels --all-namespaces'
alias kgsecwsll='kubectl get secret --watch --show-labels -l'
alias kgsecwsln='kubectl get secret --watch --show-labels --namespace'
alias kgsl='kubectl get --show-labels'
alias kgslall='kubectl get --show-labels --all-namespaces'
alias kgslallowide='kubectl get --show-labels --all-namespaces -o=wide'
alias kgslallw='kubectl get --show-labels --all-namespaces --watch'
alias kgslf='kubectl get --show-labels --recursive -f'
alias kgsll='kubectl get --show-labels -l'
alias kgsln='kubectl get --show-labels --namespace'
alias kgslowide='kubectl get --show-labels -o=wide'
alias kgslowideall='kubectl get --show-labels -o=wide --all-namespaces'
alias kgslowidef='kubectl get --show-labels -o=wide --recursive -f'
alias kgslowidel='kubectl get --show-labels -o=wide -l'
alias kgslowiden='kubectl get --show-labels -o=wide --namespace'
alias kgslw='kubectl get --show-labels --watch'
alias kgslwall='kubectl get --show-labels --watch --all-namespaces'
alias kgslwf='kubectl get --show-labels --watch --recursive -f'
alias kgslwl='kubectl get --show-labels --watch -l'
alias kgslwn='kubectl get --show-labels --watch --namespace'
alias kgsts='kubectl get statefulset'
alias kgstsall='kubectl get statefulset --all-namespaces'
alias kgstsallojson='kubectl get statefulset --all-namespaces -o=json'
alias kgstsallowide='kubectl get statefulset --all-namespaces -o=wide'
alias kgstsallowidesl='kubectl get statefulset --all-namespaces -o=wide --show-labels'
alias kgstsalloyaml='kubectl get statefulset --all-namespaces -o=yaml'
alias kgstsallsl='kubectl get statefulset --all-namespaces --show-labels'
alias kgstsallslowide='kubectl get statefulset --all-namespaces --show-labels -o=wide'
alias kgstsallslw='kubectl get statefulset --all-namespaces --show-labels --watch'
alias kgstsallw='kubectl get statefulset --all-namespaces --watch'
alias kgstsallwsl='kubectl get statefulset --all-namespaces --watch --show-labels'
alias kgstsl='kubectl get statefulset -l'
alias kgstsn='kubectl get statefulset --namespace'
alias kgstsojson='kubectl get statefulset -o=json'
alias kgstsojsonall='kubectl get statefulset -o=json --all-namespaces'
alias kgstsojsonl='kubectl get statefulset -o=json -l'
alias kgstsojsonn='kubectl get statefulset -o=json --namespace'
alias kgstsowide='kubectl get statefulset -o=wide'
alias kgstsowideall='kubectl get statefulset -o=wide --all-namespaces'
alias kgstsowideallsl='kubectl get statefulset -o=wide --all-namespaces --show-labels'
alias kgstsowidel='kubectl get statefulset -o=wide -l'
alias kgstsowiden='kubectl get statefulset -o=wide --namespace'
alias kgstsowidesl='kubectl get statefulset -o=wide --show-labels'
alias kgstsowideslall='kubectl get statefulset -o=wide --show-labels --all-namespaces'
alias kgstsowidesll='kubectl get statefulset -o=wide --show-labels -l'
alias kgstsowidesln='kubectl get statefulset -o=wide --show-labels --namespace'
alias kgstsoyaml='kubectl get statefulset -o=yaml'
alias kgstsoyamlall='kubectl get statefulset -o=yaml --all-namespaces'
alias kgstsoyamll='kubectl get statefulset -o=yaml -l'
alias kgstsoyamln='kubectl get statefulset -o=yaml --namespace'
alias kgstssl='kubectl get statefulset --show-labels'
alias kgstsslall='kubectl get statefulset --show-labels --all-namespaces'
alias kgstsslallowide='kubectl get statefulset --show-labels --all-namespaces -o=wide'
alias kgstsslallw='kubectl get statefulset --show-labels --all-namespaces --watch'
alias kgstssll='kubectl get statefulset --show-labels -l'
alias kgstssln='kubectl get statefulset --show-labels --namespace'
alias kgstsslowide='kubectl get statefulset --show-labels -o=wide'
alias kgstsslowideall='kubectl get statefulset --show-labels -o=wide --all-namespaces'
alias kgstsslowidel='kubectl get statefulset --show-labels -o=wide -l'
alias kgstsslowiden='kubectl get statefulset --show-labels -o=wide --namespace'
alias kgstsslw='kubectl get statefulset --show-labels --watch'
alias kgstsslwall='kubectl get statefulset --show-labels --watch --all-namespaces'
alias kgstsslwl='kubectl get statefulset --show-labels --watch -l'
alias kgstsslwn='kubectl get statefulset --show-labels --watch --namespace'
alias kgstsw='kubectl get statefulset --watch'
alias kgstswall='kubectl get statefulset --watch --all-namespaces'
alias kgstswallsl='kubectl get statefulset --watch --all-namespaces --show-labels'
alias kgstswl='kubectl get statefulset --watch -l'
alias kgstswn='kubectl get statefulset --watch --namespace'
alias kgstswsl='kubectl get statefulset --watch --show-labels'
alias kgstswslall='kubectl get statefulset --watch --show-labels --all-namespaces'
alias kgstswsll='kubectl get statefulset --watch --show-labels -l'
alias kgstswsln='kubectl get statefulset --watch --show-labels --namespace'
alias kgsvc='kubectl get service'
alias kgsvcall='kubectl get service --all-namespaces'
alias kgsvcallojson='kubectl get service --all-namespaces -o=json'
alias kgsvcallowide='kubectl get service --all-namespaces -o=wide'
alias kgsvcallowidesl='kubectl get service --all-namespaces -o=wide --show-labels'
alias kgsvcalloyaml='kubectl get service --all-namespaces -o=yaml'
alias kgsvcallsl='kubectl get service --all-namespaces --show-labels'
alias kgsvcallslowide='kubectl get service --all-namespaces --show-labels -o=wide'
alias kgsvcallslw='kubectl get service --all-namespaces --show-labels --watch'
alias kgsvcallw='kubectl get service --all-namespaces --watch'
alias kgsvcallwsl='kubectl get service --all-namespaces --watch --show-labels'
alias kgsvcl='kubectl get service -l'
alias kgsvcn='kubectl get service --namespace'
alias kgsvcojson='kubectl get service -o=json'
alias kgsvcojsonall='kubectl get service -o=json --all-namespaces'
alias kgsvcojsonl='kubectl get service -o=json -l'
alias kgsvcojsonn='kubectl get service -o=json --namespace'
alias kgsvcowide='kubectl get service -o=wide'
alias kgsvcowideall='kubectl get service -o=wide --all-namespaces'
alias kgsvcowideallsl='kubectl get service -o=wide --all-namespaces --show-labels'
alias kgsvcowidel='kubectl get service -o=wide -l'
alias kgsvcowiden='kubectl get service -o=wide --namespace'
alias kgsvcowidesl='kubectl get service -o=wide --show-labels'
alias kgsvcowideslall='kubectl get service -o=wide --show-labels --all-namespaces'
alias kgsvcowidesll='kubectl get service -o=wide --show-labels -l'
alias kgsvcowidesln='kubectl get service -o=wide --show-labels --namespace'
alias kgsvcoyaml='kubectl get service -o=yaml'
alias kgsvcoyamlall='kubectl get service -o=yaml --all-namespaces'
alias kgsvcoyamll='kubectl get service -o=yaml -l'
alias kgsvcoyamln='kubectl get service -o=yaml --namespace'
alias kgsvcsl='kubectl get service --show-labels'
alias kgsvcslall='kubectl get service --show-labels --all-namespaces'
alias kgsvcslallowide='kubectl get service --show-labels --all-namespaces -o=wide'
alias kgsvcslallw='kubectl get service --show-labels --all-namespaces --watch'
alias kgsvcsll='kubectl get service --show-labels -l'
alias kgsvcsln='kubectl get service --show-labels --namespace'
alias kgsvcslowide='kubectl get service --show-labels -o=wide'
alias kgsvcslowideall='kubectl get service --show-labels -o=wide --all-namespaces'
alias kgsvcslowidel='kubectl get service --show-labels -o=wide -l'
alias kgsvcslowiden='kubectl get service --show-labels -o=wide --namespace'
alias kgsvcslw='kubectl get service --show-labels --watch'
alias kgsvcslwall='kubectl get service --show-labels --watch --all-namespaces'
alias kgsvcslwl='kubectl get service --show-labels --watch -l'
alias kgsvcslwn='kubectl get service --show-labels --watch --namespace'
alias kgsvcw='kubectl get service --watch'
alias kgsvcwall='kubectl get service --watch --all-namespaces'
alias kgsvcwallsl='kubectl get service --watch --all-namespaces --show-labels'
alias kgsvcwl='kubectl get service --watch -l'
alias kgsvcwn='kubectl get service --watch --namespace'
alias kgsvcwsl='kubectl get service --watch --show-labels'
alias kgsvcwslall='kubectl get service --watch --show-labels --all-namespaces'
alias kgsvcwsll='kubectl get service --watch --show-labels -l'
alias kgsvcwsln='kubectl get service --watch --show-labels --namespace'
alias kgw='kubectl get --watch'
alias kgwall='kubectl get --watch --all-namespaces'
alias kgwallsl='kubectl get --watch --all-namespaces --show-labels'
alias kgwf='kubectl get --watch --recursive -f'
alias kgwl='kubectl get --watch -l'
alias kgwn='kubectl get --watch --namespace'
alias kgwsl='kubectl get --watch --show-labels'
alias kgwslall='kubectl get --watch --show-labels --all-namespaces'
alias kgwslf='kubectl get --watch --show-labels --recursive -f'
alias kgwsll='kubectl get --watch --show-labels -l'
alias kgwsln='kubectl get --watch --show-labels --namespace'
alias kk='kubectl kustomize'
alias klo='kubectl logs -f'
alias klon='kubectl logs -f --namespace'
alias klop='kubectl logs -f -p'
alias kp='kubectl proxy'
alias kpf='kubectl port-forward'
alias kpfn='kubectl port-forward --namespace'
alias krm='kubectl delete'
alias krmall='kubectl delete --all'
alias krmcm='kubectl delete configmap'
alias krmcmall='kubectl delete configmap --all'
alias krmcml='kubectl delete configmap -l'
alias krmcmn='kubectl delete configmap --namespace'
alias krmdep='kubectl delete deployment'
alias krmdepall='kubectl delete deployment --all'
alias krmdepl='kubectl delete deployment -l'
alias krmdepn='kubectl delete deployment --namespace'
alias krmf='kubectl delete --recursive -f'
alias krming='kubectl delete ingress'
alias krmingall='kubectl delete ingress --all'
alias krmingl='kubectl delete ingress -l'
alias krmingn='kubectl delete ingress --namespace'
alias krml='kubectl delete -l'
alias krmn='kubectl delete --namespace'
alias krmns='kubectl delete namespaces'
alias krmnsall='kubectl delete namespaces --all'
alias krmnsl='kubectl delete namespaces -l'
alias krmpo='kubectl delete pods'
alias krmpoall='kubectl delete pods --all'
alias krmpol='kubectl delete pods -l'
alias krmpon='kubectl delete pods --namespace'
alias krmsec='kubectl delete secret'
alias krmsecall='kubectl delete secret --all'
alias krmsecl='kubectl delete secret -l'
alias krmsecn='kubectl delete secret --namespace'
alias krmsts='kubectl delete statefulset'
alias krmstsall='kubectl delete statefulset --all'
alias krmstsl='kubectl delete statefulset -l'
alias krmstsn='kubectl delete statefulset --namespace'
alias krmsvc='kubectl delete service'
alias krmsvcall='kubectl delete service --all'
alias krmsvcl='kubectl delete service -l'
alias krmsvcn='kubectl delete service --namespace'
alias krun='kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias ksys='kubectl --namespace=kube-system'
alias ksysa='kubectl --namespace=kube-system apply --recursive -f'
alias ksysd='kubectl --namespace=kube-system describe'
alias ksysdcm='kubectl --namespace=kube-system describe configmap'
alias ksysdcml='kubectl --namespace=kube-system describe configmap -l'
alias ksysddep='kubectl --namespace=kube-system describe deployment'
alias ksysddepl='kubectl --namespace=kube-system describe deployment -l'
alias ksysding='kubectl --namespace=kube-system describe ingress'
alias ksysdingl='kubectl --namespace=kube-system describe ingress -l'
alias ksysdl='kubectl --namespace=kube-system describe -l'
alias ksysdpo='kubectl --namespace=kube-system describe pods'
alias ksysdpol='kubectl --namespace=kube-system describe pods -l'
alias ksysdsec='kubectl --namespace=kube-system describe secret'
alias ksysdsecl='kubectl --namespace=kube-system describe secret -l'
alias ksysdsts='kubectl --namespace=kube-system describe statefulset'
alias ksysdstsl='kubectl --namespace=kube-system describe statefulset -l'
alias ksysdsvc='kubectl --namespace=kube-system describe service'
alias ksysdsvcl='kubectl --namespace=kube-system describe service -l'
alias ksysex='kubectl --namespace=kube-system exec -i -t'
alias ksysg='kubectl --namespace=kube-system get'
alias ksysgcm='kubectl --namespace=kube-system get configmap'
alias ksysgcml='kubectl --namespace=kube-system get configmap -l'
alias ksysgcmojson='kubectl --namespace=kube-system get configmap -o=json'
alias ksysgcmojsonl='kubectl --namespace=kube-system get configmap -o=json -l'
alias ksysgcmowide='kubectl --namespace=kube-system get configmap -o=wide'
alias ksysgcmowidel='kubectl --namespace=kube-system get configmap -o=wide -l'
alias ksysgcmowidesl='kubectl --namespace=kube-system get configmap -o=wide --show-labels'
alias ksysgcmowidesll='kubectl --namespace=kube-system get configmap -o=wide --show-labels -l'
alias ksysgcmoyaml='kubectl --namespace=kube-system get configmap -o=yaml'
alias ksysgcmoyamll='kubectl --namespace=kube-system get configmap -o=yaml -l'
alias ksysgcmsl='kubectl --namespace=kube-system get configmap --show-labels'
alias ksysgcmsll='kubectl --namespace=kube-system get configmap --show-labels -l'
alias ksysgcmslowide='kubectl --namespace=kube-system get configmap --show-labels -o=wide'
alias ksysgcmslowidel='kubectl --namespace=kube-system get configmap --show-labels -o=wide -l'
alias ksysgcmslw='kubectl --namespace=kube-system get configmap --show-labels --watch'
alias ksysgcmslwl='kubectl --namespace=kube-system get configmap --show-labels --watch -l'
alias ksysgcmw='kubectl --namespace=kube-system get configmap --watch'
alias ksysgcmwl='kubectl --namespace=kube-system get configmap --watch -l'
alias ksysgcmwsl='kubectl --namespace=kube-system get configmap --watch --show-labels'
alias ksysgcmwsll='kubectl --namespace=kube-system get configmap --watch --show-labels -l'
alias ksysgdep='kubectl --namespace=kube-system get deployment'
alias ksysgdepl='kubectl --namespace=kube-system get deployment -l'
alias ksysgdepojson='kubectl --namespace=kube-system get deployment -o=json'
alias ksysgdepojsonl='kubectl --namespace=kube-system get deployment -o=json -l'
alias ksysgdepowide='kubectl --namespace=kube-system get deployment -o=wide'
alias ksysgdepowidel='kubectl --namespace=kube-system get deployment -o=wide -l'
alias ksysgdepowidesl='kubectl --namespace=kube-system get deployment -o=wide --show-labels'
alias ksysgdepowidesll='kubectl --namespace=kube-system get deployment -o=wide --show-labels -l'
alias ksysgdepoyaml='kubectl --namespace=kube-system get deployment -o=yaml'
alias ksysgdepoyamll='kubectl --namespace=kube-system get deployment -o=yaml -l'
alias ksysgdepsl='kubectl --namespace=kube-system get deployment --show-labels'
alias ksysgdepsll='kubectl --namespace=kube-system get deployment --show-labels -l'
alias ksysgdepslowide='kubectl --namespace=kube-system get deployment --show-labels -o=wide'
alias ksysgdepslowidel='kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
alias ksysgdepslw='kubectl --namespace=kube-system get deployment --show-labels --watch'
alias ksysgdepslwl='kubectl --namespace=kube-system get deployment --show-labels --watch -l'
alias ksysgdepw='kubectl --namespace=kube-system get deployment --watch'
alias ksysgdepwl='kubectl --namespace=kube-system get deployment --watch -l'
alias ksysgdepwsl='kubectl --namespace=kube-system get deployment --watch --show-labels'
alias ksysgdepwsll='kubectl --namespace=kube-system get deployment --watch --show-labels -l'
alias ksysging='kubectl --namespace=kube-system get ingress'
alias ksysgingl='kubectl --namespace=kube-system get ingress -l'
alias ksysgingojson='kubectl --namespace=kube-system get ingress -o=json'
alias ksysgingojsonl='kubectl --namespace=kube-system get ingress -o=json -l'
alias ksysgingowide='kubectl --namespace=kube-system get ingress -o=wide'
alias ksysgingowidel='kubectl --namespace=kube-system get ingress -o=wide -l'
alias ksysgingowidesl='kubectl --namespace=kube-system get ingress -o=wide --show-labels'
alias ksysgingowidesll='kubectl --namespace=kube-system get ingress -o=wide --show-labels -l'
alias ksysgingoyaml='kubectl --namespace=kube-system get ingress -o=yaml'
alias ksysgingoyamll='kubectl --namespace=kube-system get ingress -o=yaml -l'
alias ksysgingsl='kubectl --namespace=kube-system get ingress --show-labels'
alias ksysgingsll='kubectl --namespace=kube-system get ingress --show-labels -l'
alias ksysgingslowide='kubectl --namespace=kube-system get ingress --show-labels -o=wide'
alias ksysgingslowidel='kubectl --namespace=kube-system get ingress --show-labels -o=wide -l'
alias ksysgingslw='kubectl --namespace=kube-system get ingress --show-labels --watch'
alias ksysgingslwl='kubectl --namespace=kube-system get ingress --show-labels --watch -l'
alias ksysgingw='kubectl --namespace=kube-system get ingress --watch'
alias ksysgingwl='kubectl --namespace=kube-system get ingress --watch -l'
alias ksysgingwsl='kubectl --namespace=kube-system get ingress --watch --show-labels'
alias ksysgingwsll='kubectl --namespace=kube-system get ingress --watch --show-labels -l'
alias ksysgl='kubectl --namespace=kube-system get -l'
alias ksysgojson='kubectl --namespace=kube-system get -o=json'
alias ksysgojsonl='kubectl --namespace=kube-system get -o=json -l'
alias ksysgowide='kubectl --namespace=kube-system get -o=wide'
alias ksysgowidel='kubectl --namespace=kube-system get -o=wide -l'
alias ksysgowidesl='kubectl --namespace=kube-system get -o=wide --show-labels'
alias ksysgowidesll='kubectl --namespace=kube-system get -o=wide --show-labels -l'
alias ksysgoyaml='kubectl --namespace=kube-system get -o=yaml'
alias ksysgoyamll='kubectl --namespace=kube-system get -o=yaml -l'
alias ksysgpo='kubectl --namespace=kube-system get pods'
alias ksysgpol='kubectl --namespace=kube-system get pods -l'
alias ksysgpoojson='kubectl --namespace=kube-system get pods -o=json'
alias ksysgpoojsonl='kubectl --namespace=kube-system get pods -o=json -l'
alias ksysgpoowide='kubectl --namespace=kube-system get pods -o=wide'
alias ksysgpoowidel='kubectl --namespace=kube-system get pods -o=wide -l'
alias ksysgpoowidesl='kubectl --namespace=kube-system get pods -o=wide --show-labels'
alias ksysgpoowidesll='kubectl --namespace=kube-system get pods -o=wide --show-labels -l'
alias ksysgpooyaml='kubectl --namespace=kube-system get pods -o=yaml'
alias ksysgpooyamll='kubectl --namespace=kube-system get pods -o=yaml -l'
alias ksysgposl='kubectl --namespace=kube-system get pods --show-labels'
alias ksysgposll='kubectl --namespace=kube-system get pods --show-labels -l'
alias ksysgposlowide='kubectl --namespace=kube-system get pods --show-labels -o=wide'
alias ksysgposlowidel='kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
alias ksysgposlw='kubectl --namespace=kube-system get pods --show-labels --watch'
alias ksysgposlwl='kubectl --namespace=kube-system get pods --show-labels --watch -l'
alias ksysgpow='kubectl --namespace=kube-system get pods --watch'
alias ksysgpowl='kubectl --namespace=kube-system get pods --watch -l'
alias ksysgpowsl='kubectl --namespace=kube-system get pods --watch --show-labels'
alias ksysgpowsll='kubectl --namespace=kube-system get pods --watch --show-labels -l'
alias ksysgsec='kubectl --namespace=kube-system get secret'
alias ksysgsecl='kubectl --namespace=kube-system get secret -l'
alias ksysgsecojson='kubectl --namespace=kube-system get secret -o=json'
alias ksysgsecojsonl='kubectl --namespace=kube-system get secret -o=json -l'
alias ksysgsecowide='kubectl --namespace=kube-system get secret -o=wide'
alias ksysgsecowidel='kubectl --namespace=kube-system get secret -o=wide -l'
alias ksysgsecowidesl='kubectl --namespace=kube-system get secret -o=wide --show-labels'
alias ksysgsecowidesll='kubectl --namespace=kube-system get secret -o=wide --show-labels -l'
alias ksysgsecoyaml='kubectl --namespace=kube-system get secret -o=yaml'
alias ksysgsecoyamll='kubectl --namespace=kube-system get secret -o=yaml -l'
alias ksysgsecsl='kubectl --namespace=kube-system get secret --show-labels'
alias ksysgsecsll='kubectl --namespace=kube-system get secret --show-labels -l'
alias ksysgsecslowide='kubectl --namespace=kube-system get secret --show-labels -o=wide'
alias ksysgsecslowidel='kubectl --namespace=kube-system get secret --show-labels -o=wide -l'
alias ksysgsecslw='kubectl --namespace=kube-system get secret --show-labels --watch'
alias ksysgsecslwl='kubectl --namespace=kube-system get secret --show-labels --watch -l'
alias ksysgsecw='kubectl --namespace=kube-system get secret --watch'
alias ksysgsecwl='kubectl --namespace=kube-system get secret --watch -l'
alias ksysgsecwsl='kubectl --namespace=kube-system get secret --watch --show-labels'
alias ksysgsecwsll='kubectl --namespace=kube-system get secret --watch --show-labels -l'
alias ksysgsl='kubectl --namespace=kube-system get --show-labels'
alias ksysgsll='kubectl --namespace=kube-system get --show-labels -l'
alias ksysgslowide='kubectl --namespace=kube-system get --show-labels -o=wide'
alias ksysgslowidel='kubectl --namespace=kube-system get --show-labels -o=wide -l'
alias ksysgslw='kubectl --namespace=kube-system get --show-labels --watch'
alias ksysgslwl='kubectl --namespace=kube-system get --show-labels --watch -l'
alias ksysgsts='kubectl --namespace=kube-system get statefulset'
alias ksysgstsl='kubectl --namespace=kube-system get statefulset -l'
alias ksysgstsojson='kubectl --namespace=kube-system get statefulset -o=json'
alias ksysgstsojsonl='kubectl --namespace=kube-system get statefulset -o=json -l'
alias ksysgstsowide='kubectl --namespace=kube-system get statefulset -o=wide'
alias ksysgstsowidel='kubectl --namespace=kube-system get statefulset -o=wide -l'
alias ksysgstsowidesl='kubectl --namespace=kube-system get statefulset -o=wide --show-labels'
alias ksysgstsowidesll='kubectl --namespace=kube-system get statefulset -o=wide --show-labels -l'
alias ksysgstsoyaml='kubectl --namespace=kube-system get statefulset -o=yaml'
alias ksysgstsoyamll='kubectl --namespace=kube-system get statefulset -o=yaml -l'
alias ksysgstssl='kubectl --namespace=kube-system get statefulset --show-labels'
alias ksysgstssll='kubectl --namespace=kube-system get statefulset --show-labels -l'
alias ksysgstsslowide='kubectl --namespace=kube-system get statefulset --show-labels -o=wide'
alias ksysgstsslowidel='kubectl --namespace=kube-system get statefulset --show-labels -o=wide -l'
alias ksysgstsslw='kubectl --namespace=kube-system get statefulset --show-labels --watch'
alias ksysgstsslwl='kubectl --namespace=kube-system get statefulset --show-labels --watch -l'
alias ksysgstsw='kubectl --namespace=kube-system get statefulset --watch'
alias ksysgstswl='kubectl --namespace=kube-system get statefulset --watch -l'
alias ksysgstswsl='kubectl --namespace=kube-system get statefulset --watch --show-labels'
alias ksysgstswsll='kubectl --namespace=kube-system get statefulset --watch --show-labels -l'
alias ksysgsvc='kubectl --namespace=kube-system get service'
alias ksysgsvcl='kubectl --namespace=kube-system get service -l'
alias ksysgsvcojson='kubectl --namespace=kube-system get service -o=json'
alias ksysgsvcojsonl='kubectl --namespace=kube-system get service -o=json -l'
alias ksysgsvcowide='kubectl --namespace=kube-system get service -o=wide'
alias ksysgsvcowidel='kubectl --namespace=kube-system get service -o=wide -l'
alias ksysgsvcowidesl='kubectl --namespace=kube-system get service -o=wide --show-labels'
alias ksysgsvcowidesll='kubectl --namespace=kube-system get service -o=wide --show-labels -l'
alias ksysgsvcoyaml='kubectl --namespace=kube-system get service -o=yaml'
alias ksysgsvcoyamll='kubectl --namespace=kube-system get service -o=yaml -l'
alias ksysgsvcsl='kubectl --namespace=kube-system get service --show-labels'
alias ksysgsvcsll='kubectl --namespace=kube-system get service --show-labels -l'
alias ksysgsvcslowide='kubectl --namespace=kube-system get service --show-labels -o=wide'
alias ksysgsvcslowidel='kubectl --namespace=kube-system get service --show-labels -o=wide -l'
alias ksysgsvcslw='kubectl --namespace=kube-system get service --show-labels --watch'
alias ksysgsvcslwl='kubectl --namespace=kube-system get service --show-labels --watch -l'
alias ksysgsvcw='kubectl --namespace=kube-system get service --watch'
alias ksysgsvcwl='kubectl --namespace=kube-system get service --watch -l'
alias ksysgsvcwsl='kubectl --namespace=kube-system get service --watch --show-labels'
alias ksysgsvcwsll='kubectl --namespace=kube-system get service --watch --show-labels -l'
alias ksysgw='kubectl --namespace=kube-system get --watch'
alias ksysgwl='kubectl --namespace=kube-system get --watch -l'
alias ksysgwsl='kubectl --namespace=kube-system get --watch --show-labels'
alias ksysgwsll='kubectl --namespace=kube-system get --watch --show-labels -l'
alias ksyslo='kubectl --namespace=kube-system logs -f'
alias ksyslop='kubectl --namespace=kube-system logs -f -p'
alias ksysrm='kubectl --namespace=kube-system delete'
alias ksysrmall='kubectl --namespace=kube-system delete --all'
alias ksysrmcm='kubectl --namespace=kube-system delete configmap'
alias ksysrmcmall='kubectl --namespace=kube-system delete configmap --all'
alias ksysrmcml='kubectl --namespace=kube-system delete configmap -l'
alias ksysrmdep='kubectl --namespace=kube-system delete deployment'
alias ksysrmdepall='kubectl --namespace=kube-system delete deployment --all'
alias ksysrmdepl='kubectl --namespace=kube-system delete deployment -l'
alias ksysrming='kubectl --namespace=kube-system delete ingress'
alias ksysrmingall='kubectl --namespace=kube-system delete ingress --all'
alias ksysrmingl='kubectl --namespace=kube-system delete ingress -l'
alias ksysrml='kubectl --namespace=kube-system delete -l'
alias ksysrmpo='kubectl --namespace=kube-system delete pods'
alias ksysrmpoall='kubectl --namespace=kube-system delete pods --all'
alias ksysrmpol='kubectl --namespace=kube-system delete pods -l'
alias ksysrmsec='kubectl --namespace=kube-system delete secret'
alias ksysrmsecall='kubectl --namespace=kube-system delete secret --all'
alias ksysrmsecl='kubectl --namespace=kube-system delete secret -l'
alias ksysrmsts='kubectl --namespace=kube-system delete statefulset'
alias ksysrmstsall='kubectl --namespace=kube-system delete statefulset --all'
alias ksysrmstsl='kubectl --namespace=kube-system delete statefulset -l'
alias ksysrmsvc='kubectl --namespace=kube-system delete service'
alias ksysrmsvcall='kubectl --namespace=kube-system delete service --all'
alias ksysrmsvcl='kubectl --namespace=kube-system delete service -l'
alias ksysrun='kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
